"""Initial migration

Revision ID: 89f03df4ed79
Revises: 
Create Date: 2024-10-19 15:00:43.547260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f03df4ed79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auftrag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kunde', sa.String(length=100), nullable=False),
    sa.Column('adresse', sa.String(length=200), nullable=True),
    sa.Column('mieter', sa.String(length=100), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('wichtigkeit', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('erstellungsdatum', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anhang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dateiname', sa.String(length=255), nullable=False),
    sa.Column('dateipfad', sa.String(length=255), nullable=False),
    sa.Column('auftrag_id', sa.Integer(), nullable=False),
    sa.Column('erstellungsdatum', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auftrag_id'], ['auftrag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kommentar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auftrag_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('erstellungsdatum', sa.DateTime(), nullable=True),
    sa.Column('termin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auftrag_id'], ['auftrag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kommentar')
    op.drop_table('anhang')
    op.drop_table('auftrag')
    # ### end Alembic commands ###
